name: Production Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.16
#
#      - name: Authenticate to Github
#        run: git config --global url."https://${{ secrets.kiwi_token }}:x-oauth-basic@github.com/ProjectAthenaa".insteadOf "https://github.com/ProjectAthenaa"
#      - name: Download Go Modules
#        run: go mod download
#
#      - name: Run Integration Tests
#        working-directory: .
#        run: go test -v ./services...

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_KEY }}

      - name: Build container image
        run: DOCKER_BUILDKIT=1 docker build --build-arg GH_TOKEN=${{ secrets.KIWI_TOKEN }} -t  registry.digitalocean.com/athenabot/antibots/shape:latest .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials and Push Image
        run: doctl registry login --expiry-seconds 1200 && docker push registry.digitalocean.com/athenabot/antibots/shape:latest

      - name: Deploy to Kubernetes
        run: make rollout